services:
  todo.db:
    image: postgres:latest
    container_name: todo.db
    environment:
      - POSTGRES_DB=todo
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./.containers/db:/var/lib/postgresql

  todo.api:
    ports:
      - "5295:8080"
      #- "7156:8081"
    image: ${DOCKER_REGISTRY-}todoapi
    build:
      context: .
      dockerfile: ./src/ToDo.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- "ASPNETCORE_URLS": "https://+:7156;http://+:5295"
      - ASPNETCORE_URL=http://localhost
      - ASPNETCORE_HTTP_PORT= 5295
      #- "ASPNETCORE_Kestrel__Certificates__Default__Password": ""
      #- "ASPNETCORE_Kestrel__Certificates__Default__Path": "/https/aspnetapp.pfx"
      - ConnectionStrings:DefaultConnection= Host=todo.db;Port=5432;Database=todo;Username=sa;Password=postgres;Include Error Detail=true
    #volumes:
      #- ~/.aspnet/https:/https:ro
    depends_on:
      - todo.db